{% set data = load_setup_py_data() %}
# {% set version = "0.1.15" %}

package:
  name: mbg-exercise-client
  # version: {{ environ['GIT_DESCRIBE_TAG'] }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')[1:]+environ.get('GIT_DESCRIBE_NUMBER', '') }}
  # version: {{ data.get('version') }}  
  # version: {{ version }}

source:
  git_url: https://github.com/munch-group/mbg-exercise-client.git

build:
  noarch: python
  number: 0
  # script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - mbg-exercises = mbg_exercise_client:launch_exercise

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.7
    - requests
    - colorama
    - readchar
    - packaging

channels:    # write here the list of channels to look for your library dependencies
  - uibcdf
  - conda-forge
  - default

dependencies:   # Keep this block with only these two packages
  - anaconda-client
  - conda-build
  
test:
  imports:
    - mbg_exercise_client

about:
  home: https://github.com/munch-group/mbg-exercise-client
  license: MIT
  summary: 'summary'
  description: |
    Description.
